apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-devfile-template
  title: Create Devfile
  description: Create a new starter DevFile preconfigured with best practices.
  tags:
    - recommended
    - ansible
    - devfile
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - repositoryUrl
      properties:
        sourceControl:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: github.com
          enum:
            - github.com
            - gitlab.com
          enumNames:
            - 'GitHub'
            - 'GitLab'
        repositoryUrl:
          title: Source code repository URL
          type: string
          description: The repository URL where the devfile needs to be scaffolded.
          maxLength: 150
        description:
          title: Devfile description
          type: string
          description: Describe the devfile and its purpose to help other users understand what to use it for.
          maxLength: 350
  steps:
    - id: ansible
      name: Creating the Ansible devfile
      action: ansible:content:create
      input:
        repositoryUrl: '${{ parameters.repositoryUrl }}'
        description: '${{ parameters.description }}'
        applicationType: devfile
        sourceControl: '${{ parameters.sourceControl }}'

  output:
    links:
      - title: Repository
        url: ${{ steps.ansible.output.prUrl}}
